/*
 * Copyright OmniFaces
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package org.omnifaces.ai.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.omnifaces.ai.AIModality.AUDIO_ANALYSIS;
import static org.omnifaces.ai.AIModality.AUDIO_GENERATION;
import static org.omnifaces.ai.AIModality.IMAGE_ANALYSIS;
import static org.omnifaces.ai.AIModality.IMAGE_GENERATION;
import static org.omnifaces.ai.AIModality.VIDEO_ANALYSIS;
import static org.omnifaces.ai.AIModality.VIDEO_GENERATION;
import static org.omnifaces.ai.AIProvider.OPENROUTER;

import java.util.List;
import java.util.Set;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.omnifaces.ai.AIConfig;
import org.omnifaces.ai.DeliberateFailures;

/**
 * OpenRouter routes models of every vendor and publishes their modalities in a listing of its own. The listing is consulted first; the model name is what the
 * modalities are read from for as long as the listing cannot be obtained, which is what an endpoint nobody serves puts these tests on.
 */
class OpenRouterAIServiceTest {

    /** An endpoint which is no HTTP endpoint at all, so every model listing fetch fails at once without touching the network. */
    private static final String UNSERVED_ENDPOINT = "unserved:///api/v1/";

    /**
     * A listing which cannot be obtained is logged as a warning, which these tests provoke on purpose. The filter is installed once and never changed, so a
     * test running beside this one keeps every warning of its own.
     */
    @BeforeAll
    static void dropTheWarningsOfTheDeliberatelyUnservedListing() {
        DeliberateFailures.dropMessagesContaining(ModelModalitiesRegistry.class.getPackageName(), "Cannot obtain");
    }

    @Test
    void supportsModality_withoutAListing_readsTheModalitiesFromTheModelName() {
        assertTrue(newService("openai/gpt-4o").supportsModality(IMAGE_ANALYSIS), "every routed model is taken to read images");
        assertTrue(newService("google/gemini-2.5-flash-image").supportsModality(IMAGE_GENERATION));
        assertFalse(newService("openai/gpt-4o").supportsModality(IMAGE_GENERATION));
        assertTrue(newService("openai/gpt-4o-audio-preview").supportsModality(AUDIO_ANALYSIS));
        assertFalse(newService("openai/gpt-4o").supportsModality(AUDIO_ANALYSIS));
        assertTrue(newService("openai/gpt-4o-mini-tts").supportsModality(AUDIO_GENERATION));
        assertTrue(newService("openai/gpt-4o-audio-preview").supportsModality(AUDIO_GENERATION));
        assertFalse(newService("openai/gpt-4o").supportsModality(AUDIO_GENERATION));
        assertTrue(newService("qwen/qwen2.5-video-7b").supportsModality(VIDEO_ANALYSIS));
        assertFalse(newService("openai/sora-2").supportsModality(VIDEO_GENERATION), "a video generator is named after neither video nor generation");
    }

    /**
     * OpenRouter enumerates the video generators under a listing of their own, so both are consulted.
     */
    @Test
    void getModelsPaths_coverTheVideoGeneratorsBesideTheDefaultListing() {
        assertEquals(List.of("models", "models?output_modalities=video"), newService("openai/gpt-4o").getModelsPaths());
    }

    @Test
    void supportsWebSearch_isServedWhateverTheModel() {
        assertTrue(newService("openai/gpt-4o").supportsWebSearch());
    }

    /**
     * OpenRouter has no speech endpoint which its model listing enumerates, so audio is generated by an audio capable chat model instead.
     */
    @Test
    void getGenerateAudioPath_isTheChatPath() {
        var service = newService("openai/gpt-4o-audio-preview");

        assertEquals(service.getChatPath(false), service.getGenerateAudioPath());
    }

    /**
     * Neither of these OpenAI endpoints is served, so the chat model is asked instead.
     */
    @Test
    void moderationAndTranscription_areNotServedByAnEndpointOfTheirOwn() {
        var service = newService("openai/gpt-4o");

        assertFalse(service.supportsOpenAIModerationCapability(Set.of("hate")));
        assertFalse(service.supportsOpenAITranscriptionCapability());
    }

    private static OpenRouterAIService newService(String model) {
        return new OpenRouterAIService(AIConfig.of(OPENROUTER, "test-api-key").withModel(model).withEndpoint(UNSERVED_ENDPOINT));
    }

}
